# Generated by Django 5.2.5 on 2025-08-25 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('file', models.FileField(upload_to='uploads/%Y-%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_filesize', models.IntegerField(default=None, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'В очікуванні'), ('processing', 'В обробці'), ('completed', 'Готово'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('recognized_text', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('video', 'Відео'), ('audio', 'Аудіо')], max_length=10)),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_url', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('noise_cancellation', models.BooleanField(default=False)),
                ('language', models.CharField(default='uk', max_length=10)),
                ('diarisation', models.BooleanField(default=False)),
                ('file_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медіафайл',
                'verbose_name_plural': 'Медіафайли',
                'ordering': ['-upload_date'],
            },
        ),
    ]
